version: "3.8"

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_db_iitc
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: my_db
      MYSQL_USER: root_user
      MYSQL_PASSWORD: root_pass
    volumes:
      - mysql_data_volume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_iitc
    links:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql_root_password
      UPLOAD_LIMIT: 300M
volumes:
  mysql_data_volume:
